version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  restapi:
    image: survey-restapi
    depends_on:
      - mongo
      - rabbitmq
    environment:
      PORT: "8080"
      MONGODB_URI: "mongodb://mongo/test"
      RABBITMQ_URI: "amqp://rabbitmq"
    ports:
      - "8080:8080"
  worker:
    image: survey-worker
    depends_on:
      - mongo
      - rabbitmq
    environment:
      PORT: "8081"
      MONGODB_URI: "mongodb://mongo/test"
      RABBITMQ_URI: "amqp://rabbitmq"
    ports:
      - "8081:8081"
